// <auto-generated />
using System;
using LanguageLearning.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LanguageLearning.Migrations
{
    [DbContext(typeof(WordContext))]
    [Migration("20180828093759_user-validation")]
    partial class uservalidation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LanguageLearning.Models.Hiragana", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kana")
                        .IsRequired();

                    b.Property<string>("Romaji")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Hiragana");
                });

            modelBuilder.Entity("LanguageLearning.Models.JapaneseWord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definition")
                        .IsRequired();

                    b.Property<string>("Kana")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Notes");

                    b.Property<string>("PartsOfSpeech");

                    b.HasKey("ID");

                    b.ToTable("JapaneseWord");
                });

            modelBuilder.Entity("LanguageLearning.Models.Katakana", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kana")
                        .IsRequired();

                    b.Property<string>("Romaji")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Katakana");
                });

            modelBuilder.Entity("LanguageLearning.Models.KoreanWord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definition")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Notes");

                    b.Property<string>("PartsOfSpeech");

                    b.Property<string>("SoundChange");

                    b.HasKey("ID");

                    b.ToTable("KoreanWord");
                });

            modelBuilder.Entity("LanguageLearning.Models.LanguageQuiz.QuizSessionModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentLanguage");

                    b.Property<int?>("CurrentUserID");

                    b.Property<bool>("IsPractice");

                    b.Property<int>("WordLimit");

                    b.HasKey("ID");

                    b.HasIndex("CurrentUserID");

                    b.ToTable("QuizSessionModel");
                });

            modelBuilder.Entity("LanguageLearning.Models.LanguageQuiz.WordAppearances.HiraganaAppearance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HiraganaID");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("HiraganaID");

                    b.HasIndex("UserID");

                    b.ToTable("HiraganaAppearances");
                });

            modelBuilder.Entity("LanguageLearning.Models.LanguageQuiz.WordAppearances.JapaneseWordAppearance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("JapaneseWordID");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("JapaneseWordID");

                    b.HasIndex("UserID");

                    b.ToTable("JapaneseWordAppearances");
                });

            modelBuilder.Entity("LanguageLearning.Models.LanguageQuiz.WordAppearances.KatakanaAppearance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KatakanaID");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("KatakanaID");

                    b.HasIndex("UserID");

                    b.ToTable("KatakanaAppearances");
                });

            modelBuilder.Entity("LanguageLearning.Models.LanguageQuiz.WordAppearances.KoreanWordAppearance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KoreanWordID");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("KoreanWordID");

                    b.HasIndex("UserID");

                    b.ToTable("KoreanWordAppearances");
                });

            modelBuilder.Entity("LanguageLearning.Models.UserAccount.UserData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("StringifiedSalt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("ID");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("LanguageLearning.Models.LanguageQuiz.QuizSessionModel", b =>
                {
                    b.HasOne("LanguageLearning.Models.UserAccount.UserData", "CurrentUser")
                        .WithMany()
                        .HasForeignKey("CurrentUserID");
                });

            modelBuilder.Entity("LanguageLearning.Models.LanguageQuiz.WordAppearances.HiraganaAppearance", b =>
                {
                    b.HasOne("LanguageLearning.Models.Hiragana", "Hiragana")
                        .WithMany()
                        .HasForeignKey("HiraganaID");

                    b.HasOne("LanguageLearning.Models.UserAccount.UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("LanguageLearning.Models.LanguageQuiz.WordAppearances.JapaneseWordAppearance", b =>
                {
                    b.HasOne("LanguageLearning.Models.JapaneseWord", "JapaneseWord")
                        .WithMany()
                        .HasForeignKey("JapaneseWordID");

                    b.HasOne("LanguageLearning.Models.UserAccount.UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("LanguageLearning.Models.LanguageQuiz.WordAppearances.KatakanaAppearance", b =>
                {
                    b.HasOne("LanguageLearning.Models.Katakana", "Katakana")
                        .WithMany()
                        .HasForeignKey("KatakanaID");

                    b.HasOne("LanguageLearning.Models.UserAccount.UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("LanguageLearning.Models.LanguageQuiz.WordAppearances.KoreanWordAppearance", b =>
                {
                    b.HasOne("LanguageLearning.Models.KoreanWord", "KoreanWord")
                        .WithMany()
                        .HasForeignKey("KoreanWordID");

                    b.HasOne("LanguageLearning.Models.UserAccount.UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
